kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: nfs.csi.k8s.io
parameters:
  server: 172.99.0.102
  share: /vms/sno-417/pvc
  subDir: '${pvc.metadata.namespace}-${pvc.metadata.name}-${pv.metadata.name}'
reclaimPolicy: Delete
volumeBindingMode: Immediate

